workflows:
  ios-build:
    name: iOS IPA Build (YAML)

    environment:
      ios_signing:
        distribution_type: app_store
        bundle_identifier: "de.seitendorf.kneipentour"
      flutter: stable
      xcode: latest
      vars:
        LC_ALL: en_US.UTF-8
        LANG: en_US.UTF-8

    scripts:
      # --- Podfile sicherstellen (funktioniert bei dir bereits) ---
      - name: Set up code signing settings on Xcode project
        script: xcode-project use-profiles
      - name: Fix Podfile
        script: |
          echo "Rewriting Podfile..."
          rm -f ios/Podfile
          cat > ios/Podfile << 'EOF'
          platform :ios, '15.0'
          ENV['COCOAPODS_DISABLE_STATS'] = 'true'

          flutter_root = ENV['FLUTTER_ROOT']
          load File.join(flutter_root, 'packages', 'flutter_tools', 'bin', 'podhelper.rb')

          target 'Runner' do
            use_frameworks!
            use_modular_headers!
            flutter_install_all_ios_pods File.dirname(File.realpath(__FILE__))
          end

          post_install do |installer|
            installer.pods_project.targets.each do |target|
              flutter_additional_ios_build_settings(target)
            end
          end
          EOF

      # --- CocoaPods auf Version, mit der podhelper.rb klar kommt ---
      - name: Downgrade CocoaPods
        script: |
          sudo gem uninstall cocoapods --all --executables || true
          sudo gem install cocoapods -v 1.12.1
          pod --version

      # --- Flutter & Pods vorbereiten ---
      - name: Flutter clean
        script: flutter clean

      - name: Flutter pub get
        script: flutter pub get

      - name: Pod install
        script: |
          cd ios
          rm -rf Pods Podfile.lock
          pod install

      # --- iOS Release-Build (Signing macht die Codemagic-UI) ---
      - name: Flutter build ipa
        script: |
          flutter build ipa --release

    artifacts:
      - build/ios/ipa/*.ipa

    publishing:
      email:
        recipients:
          - "uli-schmidl@web.de"

code_signing:
  ios_signing:
    certificates:
      - Codemagic Cert
    provisioning_profiles:
      - Dist_xcode
