workflows:
  kneipentour_build:
    name: Kneipentour iOS & Android Build
    max_build_duration: 60
    instance_type: mac_mini_m2

    environment:
      flutter: "stable"   # oder konkret z. B. "3.22.3"
      xcode: latest
      vars:
        PACKAGE_NAME: "de.seitendorf.kneipentour"

    scripts:
      - name: 🔧 Get Flutter dependencies
        script: flutter pub get

      - name: 🧹 Clean and recreate iOS project
        script: |
          flutter clean
          flutter create --platforms=ios --overwrite .

      - name: 📦 Install CocoaPods
        script: |
          cd ios
          pod repo update
          pod install
          cd ..

      - name: ⚙️ Build iOS (unsigned)
        script: flutter build ipa --debug --no-codesign

      - name: 🔥 Build Android (Release)
        script: flutter build apk --release

    artifacts:
      - build/app/outputs/flutter-apk/app-release.apk
      - build/ios/ipa/*.ipa

    publishing:
      email:
        recipients:
          - uli-schmidl@web.de

  android_release:
    name: Android Release Build
    instance_type: linux_x2
    environment:
      vars:
        CM_KEYSTORE_PASSWORD: "test1234"
        CM_KEY_ALIAS: "mykey"
        CM_KEY_PASSWORD: "dein_key_passwort"
        CM_KEYSTORE_PATH: "my-release-key.jks"
    scripts:
      - name: 🔑 Build signed Android release
        script: |
          ./gradlew assembleRelease \
            -Pandroid.injected.signing.store.file=$KEYSTORE_PATH \
            -Pandroid.injected.signing.store.password=$KEYSTORE_PASSWORD \
            -Pandroid.injected.signing.key.alias=$KEY_ALIAS \
            -Pandroid.injected.signing.key.password=$KEY_PASSWORD
    artifacts:
      - android/app/build/outputs/**/*.apk
      - android/app/build/outputs/**/*.aab
