workflows:
  ios-build:
    name: iOS IPA Build
    environment:
      vars:
        LC_ALL: en_US.UTF-8
        LANG: en_US.UTF-8
      flutter: stable
      xcode: latest
    scripts:
      - name: Force Correct Podfile
        script: |
          echo "Fixing Podfile…"
          rm -f ios/Podfile
          cat > ios/Podfile << 'EOF'
          platform :ios, '15.0'
          ENV['COCOAPODS_DISABLE_STATS'] = 'true'

          project 'Runner', {
            'Debug' => :debug,
            'Profile' => :release,
            'Release' => :release,
          }

          flutter_root = ENV['FLUTTER_ROOT']
          load File.join(flutter_root, 'packages', 'flutter_tools', 'bin', 'podhelper.rb')

          target 'Runner' do
            use_frameworks!
            use_modular_headers!

            flutter_install_all_ios_pods File.dirname(File.realpath(__FILE__))
          end

          post_install do |installer|
            installer.pods_project.targets.each do |target|
              flutter_additional_ios_build_settings(target)
            end
          end
          EOF
      

      # ---------- CLEAN ----------
      - name: Flutter clean
        script: |
          flutter clean

      # ---------- GET PACKAGES ----------
      - name: Flutter pub get
        script: |
          flutter pub get

      # ---------- iOS PODS INSTALL ----------
      - name: Run pod install
        script: |
          cd ios
          rm -rf Pods Podfile.lock
          pod repo update
          pod install

      # ---------- BUILD IPA ----------
      - name: Build IPA
        script: |
          flutter build ipa --release

    artifacts:
      - build/ios/ipa/*.ipa

    ios_signing:
      distribution_type: app-store
      bundle_identifier: "de.seitendorf.kneipentour"
      automatic_signing: true

    publishing:
      email:
        recipients:
          - "uli-schmidl@web.DE"
