// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBsKLmyQGgTOJojqS-bv7aJH1zG93NSjwE',
    appId: '1:518982344435:web:92242a890f4cd2f7212186',
    messagingSenderId: '518982344435',
    projectId: 'kneipentour-3d44c',
    authDomain: 'kneipentour-3d44c.firebaseapp.com',
    storageBucket: 'kneipentour-3d44c.firebasestorage.app',
    measurementId: 'G-9YLDDMTRNY',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBQCkHJ5aTpRp2TDkApZddHgvyJJ7Jka8c',
    appId: '1:518982344435:android:aa18133829d980f9212186',
    messagingSenderId: '518982344435',
    projectId: 'kneipentour-3d44c',
    storageBucket: 'kneipentour-3d44c.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDUGpqM4iO-23361BRfyQGSk5Lq9QP5SCA',
    appId: '1:518982344435:ios:d207e73558a171f2212186',
    messagingSenderId: '518982344435',
    projectId: 'kneipentour-3d44c',
    storageBucket: 'kneipentour-3d44c.firebasestorage.app',
    iosBundleId: 'com.example.kneipentour',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDUGpqM4iO-23361BRfyQGSk5Lq9QP5SCA',
    appId: '1:518982344435:ios:d207e73558a171f2212186',
    messagingSenderId: '518982344435',
    projectId: 'kneipentour-3d44c',
    storageBucket: 'kneipentour-3d44c.firebasestorage.app',
    iosBundleId: 'com.example.kneipentour',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBsKLmyQGgTOJojqS-bv7aJH1zG93NSjwE',
    appId: '1:518982344435:web:bf64fed0e387ff95212186',
    messagingSenderId: '518982344435',
    projectId: 'kneipentour-3d44c',
    authDomain: 'kneipentour-3d44c.firebaseapp.com',
    storageBucket: 'kneipentour-3d44c.firebasestorage.app',
    measurementId: 'G-K72DFRMLNB',
  );
}
