platform :ios, '13.0'

use_frameworks!
use_modular_headers!

flutter_application_path = File.expand_path(File.join(__dir__, '..'))
require File.join(flutter_application_path, '.ios', 'Flutter', 'podhelper.rb')

target 'Runner' do
  flutter_ios_podfile_setup
  flutter_install_all_ios_pods(flutter_application_path)
end

post_install do |installer|
  flutter_additional_ios_build_settings(installer)
end
