platform :ios, '13.0'

use_frameworks!
use_modular_headers!

flutter_application_path = File.expand_path('../..', __FILE__)
require File.join(flutter_application_path, '.ios', 'Flutter', 'podhelper.rb')

target 'Runner' do
  flutter_install_all_ios_pods(flutter_application_path)
  target 'RunnerTests' do
    inherit! :search_paths
  end
end

post_install do |installer|
  installer.pods_project.targets.each do |target|
    flutter_additional_ios_build_settings(target)
  end
end
